[package]
name = "scheduling_system"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = "0.5"

[dependencies]
shared_messages = { path = "../shared_messages" }
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0"
calamine = "0"
regex = "1.10"
actix-web = "4"
actix-web-actors = "4"
actix-rt = "2"
actix = "0"
tokio = "1"
serde = { version = "1", features = ["derive"] } 
serde_json = "1"
priority-queue = "2"
tracing = "0"
tracing-subscriber = { version = "0", features = ["json", "env-filter"] }
tracing-appender = "0.2"
csv = "1.3"
lazy_static = "1.4.0" 
rand = "0.8"
strum = "0"
strum_macros = "0"
tracing-flame = "0.2"
colored = "2"
dotenv = "0.15"
